services:
  db:
    image: postgres:16-alpine
    container_name: italy-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASS:-password}
      POSTGRES_DB: ${DATABASE_NAME:-italy-db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:${DATABASE_PORT:-5433}:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-user} -d ${DATABASE_NAME:-italy-db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: valkey/valkey:8-alpine
    container_name: itali-redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - '127.0.0.1:${REDIS_PORT:-6379}:6379'
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      labels:
        - "image-name=itali-shop-app"
    container_name: itali-shop-app
    restart: always
    ports:
      - '${PORT:-3005}:3000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USER:-user}:${DATABASE_PASS:-password}@db:5432/${DATABASE_NAME:-italy-db}?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379

    env_file:
      - .env

  worker-sync:
    build:
      context: .
      labels:
        - "image-name=itali-shop-app"
    container_name: itali-worker-sync
    restart: always
    command: ["npx", "tsx", "app/worker.ts"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USER:-user}:${DATABASE_PASS:-password}@db:5432/${DATABASE_NAME:-italy-db}?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379

    env_file:
      - .env

  worker-price-notification:
    build:
      context: .
      labels:
        - "image-name=itali-shop-app"
    container_name: itali-worker-price-notification
    restart: always
    command: ["npx", "tsx", "app/price-notification-worker.ts"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USER:-user}:${DATABASE_PASS:-password}@db:5432/${DATABASE_NAME:-italy-db}?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379

    env_file:
      - .env

  worker-collection:
    build:
      context: .
      labels:
        - "image-name=itali-shop-app"
    container_name: itali-worker-collection
    restart: always
    command: ["npx", "tsx", "app/collection-worker.ts"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USER:-user}:${DATABASE_PASS:-password}@db:5432/${DATABASE_NAME:-italy-db}?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379

    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
