# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4975a472f8afc31d6809e4281ec1390f"
name = "mio-mio-system"
application_url = "https://development.nninc.uk"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "collections/create" ]
  uri = "/webhooks/collections/create"

  [[webhooks.subscriptions]]
  topics = [ "collections/update" ]
  uri = "/webhooks/collections/update"

  [[webhooks.subscriptions]]
  topics = [ "collections/delete" ]
  uri = "/webhooks/collections/delete"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "/webhooks/orders/cancelled"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/orders/fulfilled"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, write_metaobjects, read_metaobjects, write_translations, read_translations, write_content, read_content, write_discounts, read_discounts, write_customers, read_customers, write_orders, read_orders, write_draft_orders, read_draft_orders, write_cart_transforms, read_locales"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[app_proxy]
url = "/my-app-proxy"
subpath = "testproxy"
prefix = "apps"
