# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4975a472f8afc31d6809e4281ec1390f"
name = "mio-mio-system"
application_url = "https://app.miomio.com.ua/"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "collections/delete" ]
  uri = "/webhooks/collections/delete"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "collections/update" ]
  uri = "/webhooks/collections/update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/orders/fulfilled"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "collections/create" ]
  uri = "/webhooks/collections/create"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "/webhooks/orders/cancelled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_discounts,read_draft_orders,read_fulfillments,read_locales,read_metaobjects,read_orders,read_products,read_translations,write_cart_transforms,write_content,write_customers,write_discounts,write_draft_orders,write_fulfillments,write_metaobjects,write_orders,write_products,write_translations,write_merchant_managed_fulfillment_orders,write_assigned_fulfillment_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ 
   "https://app.miomio.com.ua/api/auth/callback",
  "https://app.miomio.com.ua/api/auth/oauth/callback",
]

[app_proxy]
url = "https://app.miomio.com.ua/my-app-proxy"
subpath = "testproxy"
prefix = "apps"
