api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "discount-by-line"
type = "function"
uid = "f0e6066f-5b21-3980-1cc7-e3ddf52419eab75bdf5d"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
